routes/web.php
<?php
use App\Purchase;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'],function(){
    Auth::routes();
    Route::get('/','MainController@index');
    Route::post('/postlogin','MainController@postlogin');
    Route::get('/dashboard','MainController@homePage');
    Route::get('/logout','MainController@logout');
    Route::get('/ola','HomeController@index');

    /*---------------------------------------------------------------*/
    Route::resource('stock','Stock\StockController');


    Route::resource('product','Product\ProductController');
    /*----------------------------------------------------------------------------------*/
    Route::resource('purchase','Purchase\PurchaseController');

    /*----------------------------------------------------------------------------------*/

    /*---------------------------------------------------------------*/

    /*---------------------------------------------------------------*/
    Route::resource('account','Account\AccountController');
    /*---------------------------------------------------------------*/
    Route::resource('category','Category\CategoryController');
    /*---------------------------------------------------------------*/
    Route::resource('brand','Brand\BrandController');
    /*---------------------------------------------------------------*/
    Route::resource('list','listController');
    /*----------------------------------------------------------------*/
    Route::get('/sale/create','Sale\SaleController@create')->name('create');
    Route::get('/sale/partialcreate','Sale\SaleController@partialcreate')->name('partialcreate');
    Route::post('/sale/addStore','Sale\SaleController@addStore')->name('addStore');
    Route::get('/sale/list','Sale\SaleController@list')->name('sale_list');
    Route::get('/getproducts','Sale\SaleController@getproducts')->name('getproducts');
    /*-------------------------------------------------------------------------------------------------------------------------*/
    Route::get('/setting/change_password','Setting\SettingController@index')->name('change_password');
    Route::post('setting/change_password_action','Setting\SettingController@change_password_action')->name('change_password_action');
    Route::get('/setting/create_profile','Setting\SettingController@create_profile')->name('create_profile');
    /*--------------------------------------------------------------------------------------------------------*/

    Route::get('/report/purchase_report','Report\ReportController@index')->name('purchase_report');
    Route::get('report','Report\ReportController@report')->name('report');
    Route::get('/report/purchase_report/pdf','Report\ReportController@pdf');
    Route::get('/report/sale_report','Report\SaleController@index');
    Route::get('/sale_report','Report\SaleController@sale_report')->name('sale_report');
    Route::get('report/sale_report/pdf','Report\SaleController@pdf')->name('pdf');
    /*---------------------------------------------------------------------------------------------------------*/





    Route::get('/downloadPDF/{id}','listController@downloadPDF');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test','listController@list')->name('list');


});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name','brand_id','categorie_id'];
}

app/Http/Controllers/Product/ProductController.php
<?php

namespace App\Http\Controllers\Product;

use App\Brand;
use App\Category;
use App\Product;
use App\OldStock;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['products'] = Product::all();
        $data['brands'] = Brand::all();
        $data['categories'] = Category::all();
        return view('product.create',$data);
    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|alpha',
            'brand_id' => 'required|exists:brands,id',
            'categorie_id' => 'required|exists:categories,id'
            ]);
        $product = new Product();
        $product['name'] = $request->get('name');
        $product['brand_id'] = $request->get('brand_id');
        $product['categorie_id'] = $request->get('categorie_id');
        $product->save();
        return redirect()->route('product.create')->with('success','Product Inserted Successful');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['products'] = Product::find($id);
        $data['brands'] = Brand::all();
        $data['categories'] = Category::all();
        return view('product.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required|alpha',
        ]);
        $product = Product::findOrFail($id);
        $product['name'] = $request->get('name');
        $product['brand_id'] = $request->get('brand_id');
        $product['categorie_id'] = $request->get('categorie_id');
        $product->save();
        return redirect()->route('product.create')->with('success','Product Update Successful');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        return redirect()->route('product.create')->with('success','Product Deleted');
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')
@section('content')
    <script>
        $(document).ready(function() {
            $('#table').DataTable({

            });
        });
    </script>
    @if(count($errors)>0)
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" id="message">
                {{$error}}
            </div>
        @endforeach
    @endif
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLable" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal col-md-12" name="myForm" action="{{route('product.store')}}" onsubmit="return validateForm()" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group ">
                            <label for="name">Product Name</label>
                            <input type="text" name="name" id="name" class="form-control">
                            <a href="" style="color: red;">{{$errors->first('name')}}</a>
                        </div>

                        <div class="form-group">
                            <label for="brand">Brand</label>
                            <select name="brand_id"  class="form-control">
                                <option>Select Brand:</option>
                                @foreach($brands as $brand)
                                    <option class="required" value="{{$brand->id}}">{{$brand->name}}</option>
                                @endforeach
                            </select>
                            <a href="" style="color: red;">{{$errors->first('brand_id')}}</a>
                        </div>
                        <div class="form-group">
                            <label for="brand">Category</label>
                            <select name="categorie_id"  class="form-control">
                                <option>Select Category:</option>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>
                            <a href="" style="color: red;">{{$errors->first('categorie_id')}}</a>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary col-md-12">Add</button>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-warning col-md-12" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header border-2 border-top border-top-primary border-primary">
            <span style="font-size: 20px;">Product</span>
            @if(Gate::check('isAdmin') || Gate::check('isManager'))
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="float: right">
                <i class="fas fa-plus"></i>  Add Product
            </button>
                @endif
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table" data-page-length='5'>
                <thead>
                <tr>
                    <th>S.No</th>
                    <th>Product Name</th>
                    <th>Brand</th>
                    <th>Categories</th>
                    @if(Gate::check('isAdmin') || Gate::check('isManager'))
                    <th>Action</th>
                        @endif
                </tr>
                </thead>

                <tbody>
                @foreach($products as $key=> $product)
                    <tr>
                        <td>{{++$key}}</td>
                        <td>{{$product->name}}</td>
                        <td>{{\App\Brand::find($product->brand_id)->name}}</td>
                        <td>{{\App\Category::find($product->categorie_id)->name}}</td>
                        @if(Gate::check('isAdmin') || Gate::check('isManager'))
                        <td>
                            <a href="{{route('product.edit',$product->id)}}" class="btn btn-primary"><i class="far fa-edit"></i></a>
                            <form action="{{route('product.destroy',$product->id)}}" method="post" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                            </form>
                        </td>
                            @endif
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>














@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')
@section('content')

    <div class="card">
        <div class="card-header border-2 border-top border-top-primary border-primary">
            <span style="font-size: 20px;">Product Edit</span>
        </div>
        <div class="card-body">
            <form action="{{route('product.update',$products->id)}}" method="post" enctype="multipart/form-data">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Product Name</label>
                    <input type="text" name="name" class="form-control" value="{{$products->name}}">
                    <a href="" style="color: red;">{{$errors->first('name')}}</a>
                </div>
                <div class="form-group">
                    <label for="brand_name">Brands</label>
                    <select name="brand_id" id="brand_id" class="form-control">
                        <option>Select Brand</option>
                        @foreach($brands as $brand)
                            <option value="{{$brand->id}}" {{$brand->id == $products->brand_id ? 'selected':''}}>{{$brand->name}}</option>
                            @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="categories_name">Categories</label>
                    <select name="categorie_id" id="categorie_id" class="form-control">
                        <option>Select Categories</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}" {{$category->id == $products->categorie_id ? 'selected':''}}>{{$category->name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>



    @endsection