routes/web.php
<?php
use App\Purchase;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'],function(){
    Auth::routes();
    Route::get('/','MainController@index');
    Route::post('/postlogin','MainController@postlogin');
    Route::get('/dashboard','MainController@homePage');
    Route::get('/logout','MainController@logout');
    Route::get('/ola','HomeController@index');

    /*---------------------------------------------------------------*/
    Route::resource('stock','Stock\StockController');


    Route::resource('product','Product\ProductController');
    /*----------------------------------------------------------------------------------*/
    Route::resource('purchase','Purchase\PurchaseController');

    /*----------------------------------------------------------------------------------*/

    /*---------------------------------------------------------------*/

    /*---------------------------------------------------------------*/
    Route::resource('account','Account\AccountController');
    /*---------------------------------------------------------------*/
    Route::resource('category','Category\CategoryController');
    /*---------------------------------------------------------------*/
    Route::resource('brand','Brand\BrandController');
    /*---------------------------------------------------------------*/
    Route::resource('list','listController');
    /*----------------------------------------------------------------*/
    Route::get('/sale/create','Sale\SaleController@create')->name('create');
    Route::get('/sale/partialcreate','Sale\SaleController@partialcreate')->name('partialcreate');
    Route::post('/sale/addStore','Sale\SaleController@addStore')->name('addStore');
    Route::get('/sale/list','Sale\SaleController@list')->name('sale_list');
    Route::get('/getproducts','Sale\SaleController@getproducts')->name('getproducts');
    /*-------------------------------------------------------------------------------------------------------------------------*/
    Route::get('/setting/change_password','Setting\SettingController@index')->name('change_password');
    Route::post('setting/change_password_action','Setting\SettingController@change_password_action')->name('change_password_action');
    Route::get('/setting/create_profile','Setting\SettingController@create_profile')->name('create_profile');
    /*--------------------------------------------------------------------------------------------------------*/

    Route::get('/report/purchase_report','Report\ReportController@index')->name('purchase_report');
    Route::get('report','Report\ReportController@report')->name('report');
    Route::get('/report/purchase_report/pdf','Report\ReportController@pdf');
    Route::get('/report/sale_report','Report\SaleController@index');
    Route::get('/sale_report','Report\SaleController@sale_report')->name('sale_report');
    Route::get('report/sale_report/pdf','Report\SaleController@pdf')->name('pdf');
    /*---------------------------------------------------------------------------------------------------------*/





    Route::get('/downloadPDF/{id}','listController@downloadPDF');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test','listController@list')->name('list');


});

resources/views/layouts/backend/footer.blade.php
<!-- ============================================================== -->
<!-- end footer -->
<!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- end wrapper  -->
<!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- end main wrapper  -->
<!-- ============================================================== -->
<!-- Optional JavaScript -->
<!-- jquery 3.3.1 -->

<script src="{{asset('assets/vendor/slimscroll/jquery.slimscroll.js')}}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="{{asset('assets/vendor/jquery/jquery-3.3.1.min.js')}}"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


<!-- bootstap bundle js -->
<script src="{{asset('assets/vendor/bootstrap/js/bootstrap.bundle.js')}}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



<!-- slimscroll js -->
<!-- main js -->

<script src="{{asset('assets/libs/js/main-js.js')}}"></script>
<!-- chart chartist js -->
<script src="{{asset('assets/vendor/charts/chartist-bundle/chartist.min.js')}}"></script>
<!-- sparkline js -->
<script src="{{asset('assets/vendor/charts/sparkline/jquery.sparkline.js')}}"></script>
<!-- morris js -->
<script src="{{asset('assets/vendor/charts/morris-bundle/raphael.min.js')}}"></script>
<script src="{{asset('assets/vendor/charts/morris-bundle/morris.js')}}"></script>
<!-- chart c3 js -->
<script src="{{asset('assets/vendor/charts/c3charts/c3.min.js')}}"></script>
<script src="{{asset('assets/vendor/charts/c3charts/d3-5.4.0.min.js')}}"></script>
<script src="{{asset('assets/vendor/charts/c3charts/C3chartjs.js')}}"></script>
<script src="{{asset('assets/libs/js/dashboard-ecommerce.js')}}"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>
</body>

</html>

resources/views/layouts/backend/head.blade.php
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.css" rel="stylesheet" />
    <link rel="stylesheet" href="{{url('lib/bootstrap/css/bootstrap.css')}}" >
    <link rel="stylesheet" href="{{asset('lib/bootstrap/css/design.css')}}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js" integrity="sha384-NaWTHo/8YCBYJ59830LTz/P4aQZK1sS0SneOgAvhsIl3zBu8r9RevNg5lHCHAuQ/" crossorigin="anonymous"></script>


    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('/assets/vendor/bootstrap/css/bootstrap.min.css')}}">
    <link href="{{asset('/assets/vendor/fonts/circular-std/style.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('/assets/libs/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/vendor/fonts/fontawesome/css/fontawesome-all.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/vendor/charts/chartist-bundle/chartist.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/vendor/charts/morris-bundle/morris.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/vendor/charts/c3charts/c3.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/vendor/fonts/flag-icon-css/flag-icon.min.css')}}">

    <title>Inventory Management System</title>
</head>

resources/views/layouts/backend/header.blade.php
<body>
<!-- ============================================================== -->
<!-- main wrapper -->
<!-- ============================================================== -->
<div class="dashboard-main-wrapper">
    <!-- ============================================================== -->
    <!-- navbar -->
    <!-- ============================================================== -->
    <div class="dashboard-header">
        <nav class="navbar navbar-expand-lg bg-white fixed-top">
            <a class="navbar-brand" href="{{url('dashboard')}}">Inventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto navbar-right-top">



                    <li class="nav-item dropdown nav-user">
                        @if(isset(Auth::user()->email))
                        <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{Auth::user()->email}}</a>
                         @else
                            <script>window.location="/";</script>
                        @endif
                            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                          @if(Gate::check('isAdmin') || Gate::check('isManager'))
                            <a class="dropdown-item" href="{{route('account.index')}}"><i class="fas fa-user mr-2"></i>Account</a>
                         @endcan
                           {{-- <a class="dropdown-item" href="#"><i class="fas fa-cog mr-2"></i>Setting</a>--}}

                            <a class="dropdown-item" href="{{url('/logout')}}"><i class="fas fa-power-off mr-2"></i>Logout</a>

                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- ============================================================== -->
    <!-- end navbar -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- left sidebar -->
    <!-- ============================================================== -->
    <div class="nav-left-sidebar sidebar-dark">
        <div class="menu-list">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="d-xl-none d-lg-none" href="{{url('/dashboard')}}">Dashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav flex-column">
                        <li class="nav-divider">
                            Home
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link active" href="{{url('/dashboard')}}"  aria-expanded="false" data-target="#submenu-1" aria-controls="submenu-1"><i class="fa fa-fw fa-user-circle"></i>Dashboard <span class="badge badge-success">6</span></a>
                           {{-- <div id="submenu-1" class="collapse submenu" style="">
                                <ul class="nav flex-column">

                                    <li class="nav-item">
                                        <a class="nav-link" href="dashboard-finance.html">Finance</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="dashboard-sales.html">Sales</a>
                                    </li>

                                </ul>
                            </div>--}}
                        </li>




                        <li class="nav-divider">
                            Menu
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('category.create')}}"   aria-expanded="false" {{--data-target="#submenu-6" aria-controls="submenu-6"--}}><i class="fas fa-user"></i> Category </a>
                            {{--<div id="submenu-6" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/blank-page.html">Profile</a>
                                    </li>

                                </ul>
                            </div>--}}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('brand.create')}}"   aria-expanded="false" {{--data-target="#submenu-6" aria-controls="submenu-6"--}}><i class="fas fa-user"></i> Brand </a>
                            {{--<div id="submenu-6" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/blank-page.html">Profile</a>
                                    </li>

                                </ul>
                            </div>--}}
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{route('stock.create')}}"   aria-expanded="false" data-target="#submenu-6" aria-controls="submenu-6"><i class="fas fa-user"></i> Stock </a>
                            {{--<div id="submenu-6" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/blank-page.html">Profile</a>
                                    </li>

                                </ul>
                            </div>--}}
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{{route('product.create')}}" aria-expanded="false" data-target="#submenu-7" aria-controls="submenu-7"><i class="fas fa-folder"></i>Products<span class="badge badge-secondary">New</span></a>
                            {{--<div id="submenu-7" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="">Items</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/email-details.html">Categories</a>
                                    </li>

                                </ul>
                            </div>--}}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('purchase.create')}}"  aria-expanded="false" data-target="#submenu-8" aria-controls="submenu-8"><i class="fas fa-fw fa-inbox"></i>Purchase <span class="badge badge-secondary">New</span></a>
                            {{--<div id="submenu-8" class="collapse submenu" style="">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/inbox.html">Daily Report</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/email-details.html">Weekly Report</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="pages/email-compose.html">Monthly Report</a>
                                    </li>

                                </ul>
                            </div>--}}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="" data-toggle="collapse"  aria-expanded="false" data-target="#submenu-9" aria-controls="submenu-9"><i class="fas fa-fw fa-inbox"></i>Sales <span class="badge badge-secondary">New</span></a>
                            <div id="submenu-9" class="collapse submenu">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{url('sale/create')}}">Sale Item</a>
                                    </li>
                                </ul>
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{route('list.create')}}">Sale List</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="" data-toggle="collapse"  aria-expanded="false" data-target="#submenu-3" aria-controls="submenu-9"><i class="fas fa-fw fa-inbox"></i>Report<span class="badge badge-secondary">New</span></a>
                            <div id="submenu-3" class="collapse submenu">
                                <ul class="nav flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{url('report/purchase_report')}}">Purchase Report</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{url('report/sale_report')}}">Sales Report</a>
                                    </li>
                                </ul>
                            </div>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{{url('logout')}}" data-toggle="collapse" aria-expanded="false" data-target="#submenu-5" aria-controls="submenu-5"><i class="fas fa-cog"></i> Settings</a>
                            <div id="submenu-5" class="collapse submenu" style="">
                                <ul class="nav flex-column">


                                   <li class="nav-item">
                                        <a class="nav-link" href="{{route('account.create')}}">Create Account</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" href="{{url('setting/change_password')}}">Change Password</a>
                                    </li>

                                </ul>
                            </div>
                        </li>




                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end left sidebar -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- wrapper  -->
    <!-- ============================================================== -->
    <div class="dashboard-wrapper">

resources/views/layouts/backend/message.blade.php
@if(session('success'))
    <div class="alert alert-success" id="message">
        {{session('success')}}
    </div>
@endif

<script>
    setTimeout(function () {
        $('#message').fadeOut('fast');
    },3000);
</script>