routes/web.php
<?php
use App\Purchase;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'],function(){
    Auth::routes();
    Route::get('/','MainController@index');
    Route::post('/postlogin','MainController@postlogin');
    Route::get('/dashboard','MainController@homePage');
    Route::get('/logout','MainController@logout');
    Route::get('/ola','HomeController@index');

    /*---------------------------------------------------------------*/
    Route::resource('stock','Stock\StockController');


    Route::resource('product','Product\ProductController');
    /*----------------------------------------------------------------------------------*/
    Route::resource('purchase','Purchase\PurchaseController');

    /*----------------------------------------------------------------------------------*/

    /*---------------------------------------------------------------*/

    /*---------------------------------------------------------------*/
    Route::resource('account','Account\AccountController');
    /*---------------------------------------------------------------*/
    Route::resource('category','Category\CategoryController');
    /*---------------------------------------------------------------*/
    Route::resource('brand','Brand\BrandController');
    /*---------------------------------------------------------------*/
    Route::resource('list','listController');
    /*----------------------------------------------------------------*/
    Route::get('/sale/create','Sale\SaleController@create')->name('create');
    Route::get('/sale/partialcreate','Sale\SaleController@partialcreate')->name('partialcreate');
    Route::post('/sale/addStore','Sale\SaleController@addStore')->name('addStore');
    Route::get('/sale/list','Sale\SaleController@list')->name('sale_list');
    Route::get('/getproducts','Sale\SaleController@getproducts')->name('getproducts');
    /*-------------------------------------------------------------------------------------------------------------------------*/
    Route::get('/setting/change_password','Setting\SettingController@index')->name('change_password');
    Route::post('setting/change_password_action','Setting\SettingController@change_password_action')->name('change_password_action');
    Route::get('/setting/create_profile','Setting\SettingController@create_profile')->name('create_profile');
    /*--------------------------------------------------------------------------------------------------------*/

    Route::get('/report/purchase_report','Report\ReportController@index')->name('purchase_report');
    Route::get('report','Report\ReportController@report')->name('report');
    Route::get('/report/purchase_report/pdf','Report\ReportController@pdf');
    Route::get('/report/sale_report','Report\SaleController@index');
    Route::get('/sale_report','Report\SaleController@sale_report')->name('sale_report');
    Route::get('report/sale_report/pdf','Report\SaleController@pdf')->name('pdf');
    /*---------------------------------------------------------------------------------------------------------*/





    Route::get('/downloadPDF/{id}','listController@downloadPDF');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test','listController@list')->name('list');


});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Category;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('category.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
             'name' => 'required|alpha'
        ]);
        $category = new Category([
           'name' => $request->get('name')
        ]);
        $category->save();
        return redirect()->route('category.create')->with('success','Record Inserted');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {

        $category = Category::find($id);
        return view('category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|alpha'
        ]);
        $category = Category::findOrFail($id);
        $category['name'] = $request->get('name');
        $category->save();
        return redirect()->route('category.create')->with('success','Update Successful');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return redirect()->route('category.create')->with('success','Category Deleted');
    }
}

resources/views/category/create.blade.php
@extends('layouts.master')
@section('content')
    <script>
        $(document).ready(function() {
            $('#table').DataTable({
            });
        });
    </script>
    @if(count($errors)>0)
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" id="message">
                {{$error}}
            </div>
        @endforeach
    @endif
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLable" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal col-md-12"  action="{{route('category.store')}}" method="post" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label for="name">Category Name</label>
                            <input type="text" name="name" id="name_id" class="form-control">
                            <a href="" style="color: red;">{{$errors->first('name')}}</a>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary col-md-12">Add</button>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-warning col-md-12" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header border-2 border-top border-top-primary border-primary">
            <span style="font-size: 20px;">Category</span>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="float: right">
                <i class="fas fa-plus"></i>  Add Category
            </button>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table" data-page-length='10'>
                <thead>
                <tr>
                    <th>S.No</th>
                    <th>Category Name</th>
                    @if(Gate::check('isAdmin') || Gate::check('isManager'))
                    <th>Action</th>
                    @endcan
                </tr>
                </thead>

                <tbody>
                @foreach($categories as $key=> $category)
                    <tr>
                        <td>{{++$key}}</td>
                        <td>{{$category->name}}</td>
                        @if(Gate::check('isAdmin') || Gate::check('isManager'))
                        <td>
                            <a href="{{route('category.edit',$category->id)}}" class="btn btn-primary"><i class="far fa-edit"></i></a>
                            <form action="{{route('category.destroy',$category->id)}}" method="post" style="display: inline-block">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                            </form>
                        </td>
                            @endif
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.master')
@section('content')

    <div class="card">
        <div class="card-header border-2 border-top border-top-primary border-primary">
            <span style="font-size: 20px;">Category Edit</span>
        </div>
        <div class="card-body">
            <form action="{{route('category.update',$category->id)}}" name="cForm" method="post" onsubmit="return validateForm()" enctype="multipart/form-data">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" class="form-control" value="{{$category->name}}">
                    <a href="" style="color: red;">{{$errors->first('name')}}</a>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary">Update</button>
                </div>




            </form>
        </div>
    </div>








    @endsection

resources/views/category/index.blade.php
@extends('layouts.master')
@section('content')
    {{--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
       <i class="fas fa-plus"></i>  Add Category
    </button>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenter" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Modal Title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">--}}
                    <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="category_name">StockID</label>
                            <input type="text" name="category_name" id="category_name" class="form-control">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-secondary">Add</button>
                        </div>
                    </form>
              {{--  </div>
            </div>
        </div>
    </div>--}}








@endsection