routes/web.php
<?php
use App\Purchase;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'],function(){
    Auth::routes();
    Route::get('/','MainController@index');
    Route::post('/postlogin','MainController@postlogin');
    Route::get('/dashboard','MainController@homePage');
    Route::get('/logout','MainController@logout');
    Route::get('/ola','HomeController@index');

    /*---------------------------------------------------------------*/
    Route::resource('stock','Stock\StockController');


    Route::resource('product','Product\ProductController');
    /*----------------------------------------------------------------------------------*/
    Route::resource('purchase','Purchase\PurchaseController');

    /*----------------------------------------------------------------------------------*/

    /*---------------------------------------------------------------*/

    /*---------------------------------------------------------------*/
    Route::resource('account','Account\AccountController');
    /*---------------------------------------------------------------*/
    Route::resource('category','Category\CategoryController');
    /*---------------------------------------------------------------*/
    Route::resource('brand','Brand\BrandController');
    /*---------------------------------------------------------------*/
    Route::resource('list','listController');
    /*----------------------------------------------------------------*/
    Route::get('/sale/create','Sale\SaleController@create')->name('create');
    Route::get('/sale/partialcreate','Sale\SaleController@partialcreate')->name('partialcreate');
    Route::post('/sale/addStore','Sale\SaleController@addStore')->name('addStore');
    Route::get('/sale/list','Sale\SaleController@list')->name('sale_list');
    Route::get('/getproducts','Sale\SaleController@getproducts')->name('getproducts');
    /*-------------------------------------------------------------------------------------------------------------------------*/
    Route::get('/setting/change_password','Setting\SettingController@index')->name('change_password');
    Route::post('setting/change_password_action','Setting\SettingController@change_password_action')->name('change_password_action');
    Route::get('/setting/create_profile','Setting\SettingController@create_profile')->name('create_profile');
    /*--------------------------------------------------------------------------------------------------------*/

    Route::get('/report/purchase_report','Report\ReportController@index')->name('purchase_report');
    Route::get('report','Report\ReportController@report')->name('report');
    Route::get('/report/purchase_report/pdf','Report\ReportController@pdf');
    Route::get('/report/sale_report','Report\SaleController@index');
    Route::get('/sale_report','Report\SaleController@sale_report')->name('sale_report');
    Route::get('report/sale_report/pdf','Report\SaleController@pdf')->name('pdf');
    /*---------------------------------------------------------------------------------------------------------*/





    Route::get('/downloadPDF/{id}','listController@downloadPDF');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/test','listController@list')->name('list');


});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/Brand/BrandController.php
<?php

namespace App\Http\Controllers\Brand;

use App\Brand;
use App\Category;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['brands'] = Brand::all();
        return view('brand.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|alpha'
        ]);
        $brand = new Brand([
            'name' => $request->get('name')
        ]);
        $brand->save();
        return redirect()->route('brand.create')->with('success','Record is Inserted');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $brands = Brand::find($id);
        return view('brand.edit',compact('brands'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|alpha'
        ]);
        $brands = Brand::findOrFail($id);
        $brands['name'] = $request->get('name');
        $brands->save();
        return redirect()->route('brand.create')->with('success','Update Successful');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $brand = Brand::findOrFail($id);
       $brand->delete();
       return redirect()->route('brand.create')->with('success','Brand Deleted');

    }
}

resources/views/brand/create.blade.php
@extends('layouts.master')
@section('content')
    @if(count($errors)>0)
        @foreach($errors->all() as $error)
            <div class="alert alert-danger" id="message">
                {{$error}}
            </div>
        @endforeach
    @endif
    <script>
        $(document).ready(function() {
            $('#table').DataTable({

            });
        });
    </script>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLable" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Brand</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal col-md-12" action="{{route('brand.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group ">
                            <label for="name">Brand Name</label>
                            <input type="text" name="name" id="name" class="form-control">
                            <a href="" style="color: red;">{{$errors->first('name')}}</a>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary col-md-12">Add</button>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-warning col-md-12" data-dismiss="modal">Close</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header border-2 border-top border-top-primary border-primary">
            <span style="font-size: 20px;">Brand</span>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="float: right">
                <i class="fas fa-plus"></i>  Add Brand
            </button>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="table" data-page-length='10'>
                <thead>
                <tr>
                    <th>S.No</th>
                    <th>Brand Name</th>
                    @if(Gate::check('isAdmin') || Gate::check('isManager'))
                    <th>Action</th>
                    @endcan
                </tr>
                </thead>

                <tbody>
                @foreach($brands as $key=> $brand)
                    <tr>
                        <td>{{++$key}}</td>
                        <td>{{$brand->name}}</td>
                        @if(Gate::check('isAdmin') || Gate::check('isManager'))
                       <td>
                            <a href="{{route('brand.edit',$brand->id)}}" class="btn btn-primary"><i class="far fa-edit"></i></a>
                           <form action="{{route('brand.destroy',$brand->id)}}" method="post" style="display: inline-block">
                               @csrf
                               @method('DELETE')
                               <button class="btn btn-danger"><i class="far fa-trash-alt"></i></button>
                           </form>
                        </td>
                                @endif
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>














@endsection

resources/views/brand/edit.blade.php
@extends('layouts.master')
@section('content')

    <div class="card">
        <div class="card-header border-2 border-top border-top-primary border-primary">
            <span style="font-size: 20px;">Brand Edit</span>
        </div>
        <div class="card-body">
            <form action="{{route('brand.update',$brands->id)}}" method="post" enctype="multipart/form-data">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Brand Name</label>
                    <input type="text" name="name" class="form-control" value="{{$brands->name}}">
                    <a href="" style="color: red;">{{$errors->first('name')}}</a>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary">Update</button>
                </div>
            </form>
        </div>
    </div>




    @endsection